### ISSUE TITLE
ontwerpen datamodel voor decks and handen

### ISSUE THREAD

**Issue by Rggam** [Rggam/Bridge-Program#7]
ontwerper van het datamodel voor het vastleggen binnen de applicatie van spelers, handen, biedverlopen en resultaten.

**Comment by basvangils** [comment]
ik neem hierin ook mee: 
-het inlezen van handen uit PBN
- het wegschrijven van handen naar PBN

**Comment by basvangils** [comment]
Ik neem het stuk mee voor 
- deck
- deal
- hand

ray, neem jij dan biedverloop en resultaat mee? overigens vind ik het handiger als er een apart issue gemaakt wordt waar alleen deck/deal/hand in zit

**Comment by Rggam** [comment]
See library file.
