### ISSUE TITLE
restructure code , put libraries in separate files

### ISSUE THREAD

**Issue by basvangils** [Rggam/Bridge-Program#8]
We need libs for the reusable parts. It could be that these become creates but at time of writing I don't know enough about that yet. The RUST book does say a few things about how to move modules/libs to separate files. We probably need modules for:

- making a deck (for 52 cards, but perhaps also make it generic enough so that it can be used for other card games as well). This includes shuffling the deck
- bridge game infrastructure. This module uses the deck module. Here we can setup deals with hands based on a randomized deck. 
- bidding module, which reads a bidding system in XML. this depends on getting a deal with 4 hands, coming out of the game infrastructure

These are initial thoughts and they will evolve as we get more experienced with RUST :)

**Comment by basvangils** [comment]
chap 7 of the book explains how this work. The idea is that there are package that contain crates that contain modules that contain the real code. Crates can be binary or library. `main.rs` is the root for the binary. `libs.rs` is the root for the library. Lots of ways to import and use (parts of) crates.

**Comment by Rggam** [comment]
Definitions defined in separate library module
