### ISSUE TITLE
add unit tests to existing code for hand definitions etc.

### ISSUE THREAD

**Issue by basvangils** [Rggam/Bridge-Program#9]
see ch11 of the book. The goal is to have unit tests for all code.

**Comment by Rggam** [comment]
Done for xml read module.

**Comment by basvangils** [comment]
voor de XML zie ik ze staan. Voor defs > src > lib.rs nog niet. Als je die ook gedaan hebt (en om hebt gebouwd naar modules) mag dit issue dicht.
